version: 0.0
os: linux
files:
 - source: /
   destination: /var/www/html/magento-test
permissions:
  - object: /var/www/html/magento-test
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 775
    type:
      - directory
  - object: /var/www/html/magento-test
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 664
    type:
      - file

  - object: /var/www/html/magento-test/Scripts
    pattern: "**"
    owner: root
    group: root
    mode: 777
    type:
      - directory

hooks:
  BeforeInstall:
    - location: Scripts/BeforeInstall.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: Scripts/AfterInstall.sh
      timeout: 180
      runas: root
